export const appFonts = {
  "Roboto-Black": require('../assets/fonts/Roboto-Black.ttf'),
  "Roboto-BlackItalic": require('../assets/fonts/Roboto-BlackItalic.ttf'),
  "Roboto-Bold": require('../assets/fonts/Roboto-Bold.ttf'),
  "Roboto-BoldItalic": require('../assets/fonts/Roboto-BoldItalic.ttf'),
  "Roboto-Italic": require('../assets/fonts/Roboto-Italic.ttf'),
  "Roboto-Light": require('../assets/fonts/Roboto-Light.ttf'),
  "Roboto-LightItalic": require('../assets/fonts/Roboto-LightItalic.ttf'),
  "Roboto-Medium": require('../assets/fonts/Roboto-Medium.ttf'),
  "Roboto-MediumItalic": require('../assets/fonts/Roboto-MediumItalic.ttf'),
  "Roboto-Regular": require('../assets/fonts/Roboto-Regular.ttf'),
  "Roboto-Thin": require('../assets/fonts/Roboto-Thin.ttf'),
  "Roboto-ThinItalic": require('../assets/fonts/Roboto-ThinItalic.ttf'),
  "Gilroy-Bold": require('../assets/fonts/Gilroy-Bold.ttf'),
  "Gilroy-ExtraBold": require('../assets/fonts/Gilroy-ExtraBold.ttf'),
  "Gilroy-Light": require('../assets/fonts/Gilroy-Light.ttf'),
  "Gilroy-Medium": require('../assets/fonts/Gilroy-Medium.ttf'),
  "Gilroy-Regular": require('../assets/fonts/Gilroy-Regular.ttf'),
  "Gilroy-SemiBold": require('../assets/fonts/Gilroy-SemiBold.ttf'),
}
