const paperFonts = {
  displayLarge: {
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0,
    fontWeight: '400',
    lineHeight: 64,
    fontSize: 57,
  },
  displayMedium: {
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0,
    fontWeight: '400',
    lineHeight: 52,
    fontSize: 45,
  },
  displaySmall: {
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0,
    fontWeight: '400',
    lineHeight: 44,
    fontSize: 36,
  },
  headlineLarge: {
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0,
    fontWeight: '400',
    lineHeight: 40,
    fontSize: 32,
  },
  headlineMedium: {
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0,
    fontWeight: '400',
    lineHeight: 36,
    fontSize: 28,
  },
  headlineSmall: {
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0,
    fontWeight: '400',
    lineHeight: 32,
    fontSize: 24,
  },
  titleLarge: {
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0,
    fontWeight: '400',
    lineHeight: 28,
    fontSize: 22,
  },
  titleMedium: {
    fontFamily: 'Roboto-Medium',
    letterSpacing: 0.15,
    fontWeight: '500',
    lineHeight: 24,
    fontSize: 16,
  },
  titleSmall: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    letterSpacing: 0.1,
    lineHeight: 20,
    fontSize: 14,
  },
  labelLarge: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    letterSpacing: 0.1,
    lineHeight: 20,
    fontSize: 14,
  },
  labelMedium: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    letterSpacing: 0.5,
    lineHeight: 16,
    fontSize: 12,
  },
  labelSmall: {
    fontFamily: 'Roboto-Medium',
    fontWeight: '500',
    letterSpacing: 0.5,
    lineHeight: 16,
    fontSize: 11,
  },
  bodyLarge: {
    letterSpacing: 0.15,
    fontWeight: '400',
    fontFamily: 'Roboto-Regular',
    lineHeight: 24,
    fontSize: 16,
  },
  bodyMedium: {
    fontWeight: '400',
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0.25,
    lineHeight: 20,
    fontSize: 14,
  },
  bodySmall: {
    fontWeight: '400',
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0.4,
    lineHeight: 16,
    fontSize: 12,
  },
  default: {
    fontFamily: 'Roboto-Regular',
    letterSpacing: 0,
    fontWeight: '400',
  },
}

export default paperFonts
